In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

Set the device variable to be either cuda or cpu

In [5]:
#device = torch.device("cuda")

device = torch.device("cpu")

print(device)

cpu


Make a random tensor (by default the tensor is created on the CPU)

In [6]:
x=torch.rand(3,3)

print(x)

tensor([[0.9408, 0.9005, 0.3259],
        [0.8699, 0.3680, 0.5107],
        [0.7346, 0.7290, 0.0621]])


Send the tensor to the device (which is going to be be the GPU if the device was set to be the GPU -- otherwise it will remain on the CPU)

In [7]:
x=x.to(device)

print(x)

tensor([[0.9408, 0.9005, 0.3259],
        [0.8699, 0.3680, 0.5107],
        [0.7346, 0.7290, 0.0621]])


Make a one layer net class

In [8]:
class one_layer_net(nn.Module):

    def __init__(self, input_size, output_size):
        super(one_layer_net , self).__init__()
        
        self.layer1 = nn.Linear( input_size, output_size , bias=False)
        
    def forward(self, x):
        scores = self.layer1(x)
        return scores

Build the net

In [9]:
net=one_layer_net(5,2)

Send all the weights of the network to the GPU

In [10]:
net = net.to(device)

Check that the matrix is indeed on the GPU

In [11]:
print(net.layer1.weight)

Parameter containing:
tensor([[ 0.2061,  0.2383,  0.4007,  0.4016,  0.1347],
        [-0.0465, -0.0341, -0.0251, -0.3616,  0.0417]], requires_grad=True)
