In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


Lets create one layer neural network with bias

In [2]:
class mynet(nn.Module):
  def __init__(self,input_size,output_size):
    super(mynet,self).__init__()

    self.mylayer=nn.Linear(input_size,output_size,bias=True)

  def forward(self,x):

    x=self.mylayer(x)
    p=F.softmax(x,dim=0)

    return p

Create an instance of a one layer net taking input of size 2 and returning output size of 2

In [3]:
net=mynet(2,2)
print(net)

mynet(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


print the parameters of the neural network

In [5]:
print(net.mylayer.weight)
print(net.mylayer.bias)


Parameter containing:
tensor([[ 0.0851,  0.3226],
        [-0.5832, -0.4228]], requires_grad=True)
Parameter containing:
tensor([-0.0643, -0.6283], requires_grad=True)
[Parameter containing:
tensor([[ 0.0851,  0.3226],
        [-0.5832, -0.4228]], requires_grad=True), Parameter containing:
tensor([-0.0643, -0.6283], requires_grad=True)]


make a vector and feed it to the network

In [7]:
x=torch.Tensor([1,1])
print(x)
p=net(x)
print(p)
print(p.sum())


tensor([1., 1.])
tensor([0.8784, 0.1216], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)
tensor([0.8784, 0.1216], grad_fn=<SoftmaxBackward>)
