In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In pytorch, networks are defined as a class

In [3]:
class mynet(nn.Module):

  def __init__(self,input_size,hidden_size,output_size):
    super(mynet, self).__init__()

    self.layer1=nn.Linear(input_size,hidden_size,bias=True)
    self.layer2=nn.Linear(hidden_size,output_size,bias=True)

  def Forward(self,x):

    x=self.layer1(x)
    x=F.relu(x)
    x=self.layer2(x)
    p=F.softmax(x,dim=0)

    return p

create something that takes an input of size 2, then transforms it into something size of 5, then into something size of 3

In [4]:
net = mynet(2,5,3)
print(net)

mynet(
  (layer1): Linear(in_features=2, out_features=5, bias=True)
  (layer2): Linear(in_features=5, out_features=3, bias=True)
)


now we are going to make an input vector and feed it to the network

In [6]:
x=torch.Tensor([1,1])
print(x)
p=net.Forward(x)
print(p)
print(p.sum())

tensor([1., 1.])
tensor([0.5307, 0.2616, 0.2077], grad_fn=<SoftmaxBackward>)
tensor(1.0000, grad_fn=<SumBackward0>)


We can access the first layer as follows

In [ ]:
print(net.layer1)

Linear(in_features=2, out_features=5, bias=True)


We can get the network weight and bias

In [8]:
print(net.layer1.weight)
print(net.layer1.bias)
print(net.layer2.weight)
print(net.layer2.bias)

Parameter containing:
tensor([[-0.2969,  0.3128],
        [ 0.2818,  0.6211],
        [ 0.6258, -0.3169],
        [-0.0673, -0.0973],
        [ 0.0778, -0.6444]], requires_grad=True)
Parameter containing:
tensor([ 0.5831,  0.5408,  0.2695,  0.3826, -0.3988], requires_grad=True)
Parameter containing:
tensor([[-0.1889,  0.1603, -0.1147, -0.1181, -0.2193],
        [ 0.0380, -0.0666, -0.3184, -0.2563, -0.0577],
        [-0.3079, -0.4045,  0.3454, -0.0759, -0.3856]], requires_grad=True)
Parameter containing:
tensor([0.3791, 0.0113, 0.0522], requires_grad=True)


alternatively, all the network parameters can be accessed by using net.parameters()

In [10]:
list_of_params=list(net.parameters())
print(list_of_params)

[Parameter containing:
tensor([[-0.2969,  0.3128],
        [ 0.2818,  0.6211],
        [ 0.6258, -0.3169],
        [-0.0673, -0.0973],
        [ 0.0778, -0.6444]], requires_grad=True), Parameter containing:
tensor([ 0.5831,  0.5408,  0.2695,  0.3826, -0.3988], requires_grad=True), Parameter containing:
tensor([[-0.1889,  0.1603, -0.1147, -0.1181, -0.2193],
        [ 0.0380, -0.0666, -0.3184, -0.2563, -0.0577],
        [-0.3079, -0.4045,  0.3454, -0.0759, -0.3856]], requires_grad=True), Parameter containing:
tensor([0.3791, 0.0113, 0.0522], requires_grad=True)]
