In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F


Lets create one layer neural network with bias

In [ ]:
class mynet(nn.Module):
  def __init__(self,input_size,output_size):
    super(mynet,self).__init__()

    ## complete here

  def forward(self,x):

    ## complete here
    ## complete here

    return p

Create an instance of a one layer net taking input of size 2 and returning output size of 2

In [ ]:
net=## complete here
print(net)

mynet(
  (mylayer): Linear(in_features=2, out_features=2, bias=True)
)


print the parameters of the neural network

In [ ]:
print(net.mylayer.weight)
print(net.mylayer.bias)

Parameter containing:
tensor([[-0.5687,  0.6961],
        [-0.1989,  0.5922]], requires_grad=True)
Parameter containing:
tensor([0.6318, 0.6830], requires_grad=True)


make a vector and feed it to the network

In [ ]:
x=## complete here
print(x)
p=net(x)
print(p)
print(p.sum())

tensor([1., 1.])
tensor([0.5524, 0.4476], grad_fn=<SoftmaxBackward>)
tensor(1., grad_fn=<SumBackward0>)
