In [1]:
import torch
import torch.nn as nn

Make a linear module that takes an input size of 5 and returns output size of 3

In [9]:
mod= nn.Linear(5,3)
print(mod)

Linear(in_features=5, out_features=3, bias=True)


lets make a random tensor of size 5

In [6]:
x=torch.rand(5)
print(x)
print(x.size())

tensor([0.0534, 0.3741, 0.3905, 0.7143, 0.9874])
torch.Size([5])


Feed it to the model

In [7]:
y=mod(x)
print(y)

tensor([ 0.5199, -0.2095, -0.3096], grad_fn=<SqueezeBackward3>)


In [11]:
print(mod.weight)
print(mod.weight.size())
print(mod.bias)
print(mod.bias.size())

Parameter containing:
tensor([[-0.4228, -0.1835,  0.3448,  0.3103,  0.3248],
        [ 0.2088, -0.3426, -0.1599, -0.3340, -0.0153],
        [-0.2592, -0.2247, -0.1126, -0.3726, -0.1092]], requires_grad=True)
torch.Size([3, 5])
Parameter containing:
tensor([-0.2787,  0.2031,  0.0173], requires_grad=True)
torch.Size([3])


We can also make a linear model without bias

In [12]:
mod2=nn.Linear(5,3,bias=False)
print(mod2)

Linear(in_features=5, out_features=3, bias=False)


In [13]:
print(mod2.weight)
print(mod2.bias)

Parameter containing:
tensor([[-0.2038,  0.0619, -0.2881, -0.1070,  0.0661],
        [ 0.0752,  0.3376,  0.0884,  0.3793,  0.2253],
        [-0.3642,  0.3778,  0.1178, -0.1891,  0.1114]], requires_grad=True)
None
