In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F 

Make a linear module without bias that takes an input size of 2 and return an output size of 3

In [2]:
mod=nn.Linear(2,3,bias=False)
print(mod)

Linear(in_features=2, out_features=3, bias=False)


Print the internal parameters

In [3]:
print(mod.weight)
print(mod.bias)

Parameter containing:
tensor([[-0.0403, -0.5048],
        [-0.5352,  0.4461],
        [ 0.2418, -0.6535]], requires_grad=True)
None


make a vector and feed it to your linear module

In [ ]:
x=torch.Tensor([1,1])
print(x)
y=mod(x)
print(y)

tensor([1., 1.])
tensor([ 1.2645, -0.0771, -0.2106], grad_fn=<SqueezeBackward3>)
